server:
  port: 8081
spring:
  data:
    mongodb:
      database: stock
logging:
  #配置日志文件路径
#  path: D:\temp\log\test-project.log
  level:
    org.great: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.mongodb: info